# 合并 ODB 生成的单表 SQL 为 init_all.sql（由 CMake configure_file 生成到 build/）
# 模板变量：@SQL_CODE_DIR@
set(TABLE_ORDER user relation chat_session message friend_apply chat_session_member)
set(SQL_CODE_DIR "@SQL_CODE_DIR@")
set(BQ [[`]])
set(INIT_HEADER
"-- Auto-generated by CMake from ODB schema. Do not edit manually.
-- Run 'make' or 'cmake --build . --target gen_init_all' to regenerate.

-- 创建数据库
CREATE DATABASE IF NOT EXISTS ${BQ}chen_im${BQ} DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE ${BQ}chen_im${BQ};

")
set(OUTPUT_CONTENT "${INIT_HEADER}")
foreach(TBL ${TABLE_ORDER})
  set(SQL_FILE "${SQL_CODE_DIR}/${TBL}.sql")
  if(EXISTS "${SQL_FILE}")
    file(READ "${SQL_FILE}" TBL_CONTENT)
    string(REPLACE "ENGINE=InnoDB" "ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci" TBL_CONTENT "${TBL_CONTENT}")
    set(OUTPUT_CONTENT "${OUTPUT_CONTENT}\n-- ${TBL} 表\n${TBL_CONTENT}\n")
  else()
    message(WARNING "SQL file not found: ${SQL_FILE}")
  endif()
endforeach()
file(WRITE "${SQL_CODE_DIR}/init_all.sql" "${OUTPUT_CONTENT}")
message(STATUS "Generated ${SQL_CODE_DIR}/init_all.sql")
