# 基础镜像
FROM ubuntu:20.04

# 工作路径
WORKDIR /im
RUN mkdir -p /im/logs
RUN mkdir -p /im/data
RUN mkdir -p /im/conf
RUN mkdir -p /im/bin

# 将可执行文件拷贝到镜像中
COPY ./build/user_server /im/bin

# 将配置文件拷贝到镜像中
COPY ./user_server.conf /im/conf

# 将可执行程序的依赖拷贝到docker容器中的lib目录中
COPY ./build/depends /lib/x86_64-linux-gnu/

# 容器启动时直接启动服务进程，带上配置文件
CMD /im/bin/user_server -flagfile=/im/conf/user_server.conf