/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

DROP TABLE IF EXISTS `Class`;

DROP TABLE IF EXISTS `Student`;

CREATE TABLE `Student` (
  `stu_id` BIGINT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `name` TEXT NOT NULL,
  `age` SMALLINT UNSIGNED NULL,
  `class_id` BIGINT UNSIGNED NOT NULL)
 ENGINE=InnoDB;

CREATE INDEX `class_id_i`
  ON `Student` (`class_id`);

CREATE TABLE `Class` (
  `class_id` BIGINT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `class_name` TEXT NOT NULL)
 ENGINE=InnoDB;

