/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

DROP TABLE IF EXISTS `chat_session`;
-- 聊天会话表：描述一个聊天会话，但是不存放聊天消息和成员信息
CREATE TABLE `chat_session` (
  `id` BIGINT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT, -- 唯一的自增id：只是用来计数，和业务无关，不用画在ER图里
  `chat_session_id` varchar(64) NOT NULL, -- 聊天会话id：用来唯一标识一个会话
  `chat_session_name` varchar(64) NOT NULL, -- 会话名称
  `chat_session_type` tinyint NOT NULL) -- 会话类型：1. 单人聊天 2. 群聊
 ENGINE=InnoDB;

CREATE UNIQUE INDEX `chat_session_id_i`
  ON `chat_session` (`chat_session_id`);